// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fizcaboskujxfhvdyuun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpemNhYm9za3VqeGZodmR5dXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjI4NzAsImV4cCI6MjA2NTk5ODg3MH0.5A1KNUjjhKYgTLcetnwLqySy7Su7MMNdoly_V5jEgUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);